name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*'

  pull_request:

jobs:
  Test:
    name: HelloWorld
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: |
          echo "HELLO WOLRD"